# Generated by Django 5.2.15 on 2026-06-24 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('organizations', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_membership', to='departments.department')),
                ('organization_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_membership', to='organizations.membership')),
            ],
            options={
                'unique_together': {('department', 'organization_membership')},
            },
        ),
    ]
