# Generated by Django 5.2.15 on 2026-06-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_departmentmembership'),
        ('organizations', '0002_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmembership',
            name='organization_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='organizations.membership'),
        ),
    ]
