# Generated by Django 5.2.15 on 2026-07-13 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_departmentmembership_organization_membership'),
        ('organizations', '0003_alter_membership_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='departmentmembership',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='departmentmembership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='departments.department'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_department_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(fields=('department', 'organization_membership'), name='unique_department_membership'),
        ),
        migrations.AlterModelTable(
            name='departmentmembership',
            table='department_memberships',
        ),
    ]
